// Generated by CoffeeScript 1.7.1
var DBInterface, MySqlDB,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

DBInterface = require('../db_interface');

MySqlDB = (function(_super) {
  __extends(MySqlDB, _super);

  function MySqlDB() {
    return MySqlDB.__super__.constructor.apply(this, arguments);
  }

  MySqlDB.prototype.pull = function(env) {
    if (env == null) {
      env = 'local';
    }
    console.log(this.config);
    return console.log("Pull the asd contents from '" + env + "'?");
  };

  MySqlDB.prototype.push = function(env) {
    if (env == null) {
      env = 'local';
    }
    return pass;
  };

  return MySqlDB;

})(DBInterface);

module.exports = MySqlDB;
