// Generated by CoffeeScript 1.7.1
var DBInterface, call, dbConfig, dbConfigFileName, dbObj, directory, errors, fs, pJson, path, program;

program = require('commander');

fs = require('fs');

pJson = require('../package.json');

path = require('path');

program.version(pJson.version).option('-d, --dir <dir>', 'Version control directory').option('-e, --env <env>', 'Version control environment').option('--pull', 'Pull from the databse').option('--push', 'Push to the database').parse(process.argv);

directory = process.cwd();

if (program.dir) {
  directory = path.resolve(process.cwd(), program.dir);
}

process.chdir(directory);

dbConfigFileName = directory + '/dbconfig.json';

if (!fs.existsSync(dbConfigFileName)) {
  console.log("Cannot find the configuation file. Please create one, or use the proper directory. \nMore info at http://dgit.openly.io/doc/config.\n");
  process.exit(1);
}

dbConfig = require(dbConfigFileName);

errors = [];

DBInterface = require("./lib/" + dbConfig.type);

dbObj = new DBInterface(dbConfig, directory);

call = function() {};

if (program.pull) {
  call = dbObj.pull;
} else if (program.push) {
  call = dbObj.push;
}

call.call(dbObj, program.env, function(e) {
  if (errors.length > 0) {
    return console.log('Error', errors);
  } else {
    return console.log('Successfully Done');
  }
});
