// Generated by CoffeeScript 1.7.1
var config, dbConfig, dbConfigFileName, directory, errors, fs, pJson, program, _fn, _i, _len;

program = require('commander');

fs = require('fs');

pJson = require('../package.json');

program.version(pJson.version).option('-d, --dir <dir>', 'Version control directory').option('--pull', 'Pull from the databse').option('--push', 'Push to the database').parse(process.argv);

directory = process.cwd() + '/' + program.dir;

dbConfigFileName = directory + '/dbconfig.json';

if (!fs.existsSync(dbConfigFileName)) {
  console.log("Cannot find the configuation file. Please create one, or use the proper directory. \nMore info at http://dgit.openly.io/doc/config.\n");
  process.exit(1);
}

dbConfig = require(dbConfigFileName);

errors = [];

_fn = function(config) {
  var DBInterface, dbObj, error;
  try {
    DBInterface = require("./lib/" + config.type);
    dbObj = new DBInterface(config);
    if (program.pull) {
      return dbObj.pull();
    } else if (program.push) {
      return dbObj.push();
    }
  } catch (_error) {
    error = _error;
    return errors.push(error);
  }
};
for (_i = 0, _len = dbConfig.length; _i < _len; _i++) {
  config = dbConfig[_i];
  _fn(config);
}

if (errors.length > 0) {
  console.log('Error happened', errors);
} else {
  console.log('Successfully Done');
}
